/**
 * Destinos da vitrine de roteiros (/roteiro/[destino]).
 *
 * Cada um vira uma pagina indexavel — "roteiro 2 dias em Gramado, quanto
 * custa" — que e a porta de entrada mais barata que o Planvoro tem: quem
 * busca isso esta planejando uma viagem agora. A ordem e a de prioridade:
 * o cron gera os primeiros da lista que ainda nao tem pagina.
 *
 * O nome vai com estado ou pais porque vira o titulo da pagina no Google
 * e desfaz ambiguidade ("Porto, Portugal" x "Porto Seguro, Bahia").
 */
export const DESTINOS_VITRINE = [
  "Gramado, Rio Grande do Sul",
  "Florianópolis, Santa Catarina",
  "Porto de Galinhas, Pernambuco",
  "Foz do Iguaçu, Paraná",
  "Paris, França",
  "Orlando, Estados Unidos",
  "Maceió, Alagoas",
  "Natal, Rio Grande do Norte",
  "Bariloche, Argentina",
  "Bonito, Mato Grosso do Sul",
  "Jericoacoara, Ceará",
  "Porto Seguro, Bahia",
  "Madri, Espanha",
  "Cancún, México",
  "João Pessoa, Paraíba",
  "Búzios, Rio de Janeiro",
  "Campos do Jordão, São Paulo",
  "Londres, Inglaterra",
  "Miami, Estados Unidos",
  "Balneário Camboriú, Santa Catarina",
  "Belo Horizonte, Minas Gerais",
  "Montevidéu, Uruguai",
  "Paraty, Rio de Janeiro",
  "Fernando de Noronha, Pernambuco",
  "Barcelona, Espanha",
  "Porto, Portugal",
  "Brasília, Distrito Federal",
  "Manaus, Amazonas",
  "Lençóis Maranhenses, Maranhão",
  "Chapada Diamantina, Bahia",
  "Cusco, Peru",
  "Punta del Este, Uruguai",
  "Arraial do Cabo, Rio de Janeiro",
  "Porto Alegre, Rio Grande do Sul",
  "Ilhabela, São Paulo",
  "Amsterdã, Holanda",
  "Florença, Itália",
  "Morro de São Paulo, Bahia",
  "Maragogi, Alagoas",
  "Mendoza, Argentina",
  "Lima, Peru",
  "Cartagena, Colômbia",
  "São Luís, Maranhão",
  "Tiradentes, Minas Gerais",
  "Petrópolis, Rio de Janeiro",
  "Ubatuba, São Paulo",
  "Pipa, Rio Grande do Norte",
  "Chapada dos Veadeiros, Goiás",
  "Veneza, Itália",
  "Milão, Itália",
  "Berlim, Alemanha",
  "Praga, República Tcheca",
  "Atenas, Grécia",
  "Istambul, Turquia",
  "Dubai, Emirados Árabes Unidos",
  "Punta Cana, República Dominicana",
  "Cidade do México, México",
  "Las Vegas, Estados Unidos",
  "Aracaju, Sergipe",
  "Vitória, Espírito Santo",
  "Blumenau, Santa Catarina",
  "Caldas Novas, Goiás",
  "Canela, Rio Grande do Sul",
  "Holambra, São Paulo",
] as const;
